POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o video 01",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/97f2d761-4e71-4169-ae02-637350853871
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 01",
  "duration": 180
}

###

DELETE  http://localhost:3333/videos/97f2d761-4e71-4169-ae02-637350853871